# https://github.com/actions/starter-workflows/blob/main/automation/greetings.yml
name: Greetings
on:
  - pull_request_target
  - issues
jobs:
  greeting:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thank you for opening this issue! 🎉'
          pr-message: 'Thank you for opening this pull request! 🎉'
