name: GH Pages Workflow
on:
  push:
    branches: ['dev']
  workflow_dispatch: {}
jobs:
  pitest-linux:
    if: github.event.pull_request.draft == false
    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
    # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
    concurrency:
      group: pages
      cancel-in-progress: false
    permissions:
      contents: write
      pages: write
      id-token: write
    name: github pages job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources Step
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ./.github/actions/ci-setup-node
        name: Setup CI environment
        with:
          install_scripts: 'false'
          install_playwright: 'false'
      - name: Build docs
        run: pnpm docs:build
      # - name: Build everything
      #   run: nx run-many -t build
      # - name: Build javadoc Step
      #   run: ./gradlew javadoc
      # - name: Move Pitest step
      #   run: mv ./build/reports/pitest ./docs/gh-pages/pit
      # - name: Move javadoc step
      #   run: mv ./build/docs/javadoc ./docs/gh-pages/docs
      - name: Deploy Pitest to GitHub Pages Step
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        if: github.ref == 'refs/heads/dev'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/web/.vitepress/dist
