name: Close stale issues and PR Workflow
on:
  schedule:
    - cron: '30 1 * * *' # every day at 1:30am
jobs:
  stale:
    name: Close stale issues and PR job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9
        name: Close stale issues and PR step
        with:
          stale-issue-message:
            'This issue is stale because it has been open 30 days with no
            activity. Remove stale label or comment.'
          stale-pr-message:
            'This PR is stale because it has been open 45 days with no activity.
            Remove stale label or comment.'
          close-issue-message:
            'This issue was closed because it has been stalled for 5 days with
            no activity.'
          days-before-stale: 30
          days-before-close: -1
          days-before-pr-close: -1
